# Example configuration for GitLab MR Conflict Detector

gitlab:
  # GitLab instance URL
  url: https://gitlab.example.com
  
  # Personal access token with api scope
  token: glpat-xxxxxxxxxxxxxxxxxxxx
  
  # Project ID (numeric) - use either this or projectPath
  projectId: 123
  
  # Project path (namespace/project-name) - alternative to projectId
  # projectPath: my-group/my-project
  
  # Request timeout in seconds
  timeoutSeconds: 30
  
  # Verify SSL certificates
  verifySSL: true

# Conflict detection configuration
detection:
  # Fetch latest changes before detection
  fetchBeforeDetection: true
  
  # Detection sensitivity level
  # STRICT: Detect all possible conflicts including whitespace
  # NORMAL: Standard conflict detection (default)
  # PERMISSIVE: Only detect significant conflicts
  sensitivity: NORMAL
  
  # Use recursive merge strategy for complex histories
  useRecursiveMerge: true
  
  # Maximum number of conflict sections to analyze per file
  maxConflictSections: 100

# File filtering configuration
fileFilter:
  # Patterns for files to include (glob syntax)
  includePatterns:
    - "**/*.java"
    - "**/*.kt"
    - "**/*.js"
    - "**/*.ts"
    - "**/*.py"
    - "**/*.rb"
    - "**/*.go"
    - "**/*.rs"
    - "**/*.cpp"
    - "**/*.c"
    - "**/*.h"
    - "**/*.hpp"
    - "**/*.cs"
    - "**/*.php"
    - "**/*.scala"
    - "**/*.clj"
    - "**/*.sql"
    - "**/*.xml"
    - "**/*.json"
    - "**/*.yaml"
    - "**/*.yml"
    - "**/*.md"
    - "**/*.txt"
    - "**/*.properties"
    - "**/*.conf"
    - "**/*.config"
    - "**/*.sh"
    - "**/*.bat"
    - "**/*.ps1"
    - "**/Dockerfile"
    - "**/Makefile"
    - "**/*.gradle"
    - "**/*.gradle.kts"
    - "**/pom.xml"
    - "**/package.json"
    - "**/requirements.txt"
    - "**/Cargo.toml"
    - "**/go.mod"
  
  # Patterns for files to exclude (glob syntax)
  excludePatterns:
    # Version control
    - "**/.git/**"
    - "**/.svn/**"
    - "**/.hg/**"
    
    # Build outputs
    - "**/target/**"
    - "**/build/**"
    - "**/dist/**"
    - "**/out/**"
    - "**/bin/**"
    - "**/.gradle/**"
    - "**/node_modules/**"
    - "**/vendor/**"
    - "**/__pycache__/**"
    - "**/.pytest_cache/**"
    - "**/coverage/**"
    - "**/.nyc_output/**"
    
    # IDE files
    - "**/.idea/**"
    - "**/.vscode/**"
    - "**/*.iml"
    - "**/*.ipr"
    - "**/*.iws"
    - "**/.project"
    - "**/.classpath"
    - "**/.settings/**"
    
    # OS files
    - "**/.DS_Store"
    - "**/Thumbs.db"
    - "**/*.tmp"
    - "**/*.temp"
    - "**/*.swp"
    - "**/*.swo"
    - "**/*~"
    
    # Compiled files
    - "**/*.class"
    - "**/*.jar"
    - "**/*.war"
    - "**/*.ear"
    - "**/*.exe"
    - "**/*.dll"
    - "**/*.so"
    - "**/*.dylib"
    - "**/*.o"
    - "**/*.obj"
    - "**/*.pyc"
    - "**/*.pyo"
    
    # Logs and temporary files
    - "**/*.log"
    - "**/logs/**"
    - "**/*.pid"
    - "**/*.lock"
    
    # Package files
    - "**/*.zip"
    - "**/*.tar"
    - "**/*.tar.gz"
    - "**/*.tgz"
    - "**/*.rar"
    - "**/*.7z"
    
    # Media files (usually binary and large)
    - "**/*.jpg"
    - "**/*.jpeg"
    - "**/*.png"
    - "**/*.gif"
    - "**/*.bmp"
    - "**/*.ico"
    - "**/*.svg"
    - "**/*.mp3"
    - "**/*.mp4"
    - "**/*.avi"
    - "**/*.mov"
    - "**/*.wmv"
    - "**/*.pdf"
    - "**/*.doc"
    - "**/*.docx"
    - "**/*.xls"
    - "**/*.xlsx"
    - "**/*.ppt"
    - "**/*.pptx"
  
  # Case-sensitive pattern matching
  caseSensitive: true
  
  # Follow symbolic links
  followSymlinks: false
  
  # Maximum file size to analyze (in bytes)
  # 10MB = 10 * 1024 * 1024 = 10485760
  maxFileSizeBytes: 10485760

# Force pass all conflicts (useful for testing or emergency deployments)
forcePass: false

