# Minimal configuration for quick setup

gitlab:
  url: https://gitlab.com
  token: your-access-token-here
  projectId: 123

# Use default settings for everything else
# This will:
# - Use NORMAL sensitivity
# - Include common source code files
# - Exclude build artifacts and system files
# - Fetch before detection
# - Use recursive merge analysis

